HeatTemplateFormatVersion: '2012-12-12'
Description: 'Block Storage'
Parameters:
  AdminPassword:
    Default: unset
    Description: The password for the keystone admin account, used for monitoring, querying neutron etc.
    Type: String
    NoEcho: true
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  CinderPassword:
    Default: unset
    Description: The password for the cinder service account, used by cinder-api.
    Type: String
    NoEcho: true
  KeystoneHost:
    Type: String
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
    Default: "guest"
    NoEcho: true
  NeutronHost:
    Type: String
  NeutronDSN:
    Type: String
  NeutronBridgeMappings:
    Type: String
  NeutronNetworkVLANRanges:
    Type: String
  NeutronNetworkType:
    Type: String
  NeutronEnableTunnelling:
    Type: String
  MySQLHost:
    Type: String
Resources:
  BlockStorage0:
    Type: OS::Nova::Server
    Properties:
      image:
        {Ref: BlockStorageImage}
      flavor: {Ref: Flavor}
      key_name: {Ref: KeyName}
    Metadata:
      os-collect-config:
        cfn:
          access_key_id:
            Ref: BlockStorageKey
          secret_access_key:
            Fn::GetAtt: [ BlockStorageKey, SecretAccessKey ]
          stack_name: {Ref: 'AWS::StackName'}
          path: BlockStorage0Config.Metadata
      OpenStack::ImageBuilder::Elements: [ cinder ]
  BlockStorage0Config:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: '0'
      ImageId: '0'
    Metadata:
      os-collect-config:
        cfn:
          access_key_id:
            Ref: BlockStorageKey
          secret_access_key:
            Fn::GetAtt: [ BlockStorageKey, SecretAccessKey ]
          stack_name: {Ref: 'AWS::StackName'}
          path: BlockStorage0Config.Metadata
      keystone:
        host: {Ref: KeystoneHost}
      cinder:
        db: {"Fn::Join": ['', ['mysql://cinder:unset@', {Ref: MySQLHost}, '/cinder']]}
        volume_size_mb: '5000'
        service-password:
          Ref: CinderPassword
        volume: 'true'
      neutron:
        host: {Ref: NeutronHost}
        ovs_db: {Ref: NeutronDSN}
        ovs:
          local_ip:
            Fn::Select:
              - 0
              - Fn::Select:
                - ctlplane
                - Fn::GetAtt:
                  - BlockStorage0
                  - networks
          tenant_network_type: {Ref: NeutronNetworkType}
          network_vlan_ranges: {Ref: NeutronNetworkVLANRanges}
          bridge_mappings: {Ref: NeutronBridgeMappings}
          enable_tunneling: {Ref: NeutronEnableTunnelling}
        service-password:
          {Ref: AdminPassword}
      admin-password: {Ref: AdminPassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      interfaces:
        control: {Ref: NeutronPublicInterface}
