Description: 'Ironic: Bare Metal provisioning, API and Conductor services.'
Parameters:
  IronicPassword:
    Type: String
    Description: Ironic password for keystone access
    NoEcho: true
Resources:
  ironic:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::Role: undercloudConfig
      ironic:
        db: mysql://ironic:unset@localhost/ironic
        service-password: {Ref: IronicPassword}
