Description: 'Swift-common: OpenStack object storage common configurations'
Parameters:
  SwiftHashSuffix:
    Default: unset
    Description: A random string to be used as a salt when hashing to determine mappings in the ring.
    Type: String
    NoEcho: true
  SwiftPassword:
    Default: unset
    Description: The password for the swift service account, used by the swift proxy services.
    Type: String
    NoEcho: true
Resources:
  notcomputeConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      swift:
        devices:
          Fn::Join:
            - ''
            - - 'r1z1-'
              - Fn::Select:
                - 0
                - Fn::Select:
                  - 'ctlplane'
                  - Fn::GetAtt:
                    - notcompute
                    - networks
              - ':%PORT%/d1'
        hash:
          Ref: SwiftHashSuffix
        part-power: 10
        replicas: 1
        service-password:
          Ref: SwiftPassword
