Parameters:
  NeutronPublicInterface:
    Default: eth0
    Description: What interface to bridge onto br-ex for network nodes.
    Type: String
  PowerManager:
    Default: nova.virt.baremetal.virtual_power_driver.VirtualPowerManager
    Description: Bare metal power manager driver.
    Type: String
  PowerUserName:
    Default: stack
    Description: What username to ssh to the virtual power host with.
    Type: String
Resources:
  undercloudConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      nova:
        compute_hostname: undercloud
        compute_driver: baremetal.driver.BareMetalDriver
        db: mysql://nova:unset@localhost/nova
        host: 127.0.0.1
        metadata-proxy: false
        tuning:
          ram_allocation_ratio: 1.0
          reserved_host_memory_mb: 0
        baremetal:
          use_file_injection: "False"
          arch:
            Ref: BaremetalArch
          db: mysql://nova:unset@localhost/nova_bm
          power_manager:
            Ref: PowerManager
          pxe_deploy_timeout: 2400
          virtual_power:
            user:
              Ref: PowerUserName
            key: /opt/stack/boot-stack/virtual-power-key
            ssh_host: 192.168.122.1
            type: virsh
        service-password:
          Ref: NovaPassword
