Parameters:
  C:
    Type: String
    Default: test3
  resource2Image:
    Type: String
    Default: resource2
Resources:
  notcomputeConfigMixin:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::Role: notcomputeConfig
      c: {Ref: C}
  resource2:
    Type: OS::Nova::Server
    Properties:
      flavor: test_flavor
      image: {Ref: resource2Image}
      key_name: test_key
