Description: examples/launchconfig1.yaml,examples/launchconfig2.yaml
HeatTemplateFormatVersion: '2012-12-12'
Parameters:
  A:
    Default: test1
    Type: String
  B:
    Default: test2
    Type: String
  C:
    Default: test3
    Type: String
  resource1Image:
    Default: resource1
    Type: String
  resource2Image:
    Default: resource2
    Type: String
Resources:
  notcomputeConfig:
    Metadata:
      OpenStack::Role: notcomputeConfig
      a:
        Ref: A
      b:
        Ref: B
      c:
        Ref: C
    Type: AWS::AutoScaling::LaunchConfiguration
  resource1:
    Properties:
      flavor: test_flavor
      image:
        Ref: resource1Image
      key_name: test_key
    Type: OS::Nova::Server
  resource2:
    Properties:
      flavor: test_flavor
      image:
        Ref: resource2Image
      key_name: test_key
    Type: OS::Nova::Server
