Parameters:
  A:
    Type: String
    Default: test1
  B:
    Type: String
    Default: test2
  resource1Image:
    Type: String
    Default: resource1
Resources:
  notcomputeConfigBase:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::Role: notcomputeConfig
      a: {Ref: A}
      b: {Ref: B}
  resource1:
    Type: OS::Nova::Server
    Properties:
      flavor: test_flavor
      image: {Ref: resource1Image}
      key_name: test_key
